[package]
name = "wgpu-remote-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Wire format for proxying wgpu calls to a remote GPU."

[dependencies]
serde.workspace = true
bincode.workspace = true
bytes.workspace = true
thiserror.workspace = true
wgpu-types.workspace = true
